# ==============================================================================
# EXAMPLE WORKFLOW FOR PLUGIN REPOSITORIES
# ==============================================================================
# This is a template workflow for repositories that contain Command Launcher plugins.
# Copy this file to YOUR plugin repository at: .github/workflows/release.yml
#
# DO NOT use this in the cola-plugin-action repository itself!
# ==============================================================================

name: Tag-Based Plugin Release

# This workflow triggers on version tags (e.g., v1.0.0, v2.1.0)
# Use this for semantic versioning releases

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  pages: write

jobs:
  release:
    name: Build and Release Plugins
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Validate plugins
        uses: criteo/cola-plugin-action@v1
        with:
          plugins-directory: 'plugins'
          validate-only: 'true'

      - name: Package plugins (tar.gz + OCI)
        id: package
        uses: criteo/cola-plugin-action@v1
        with:
          plugins-directory: 'plugins'
          package-format: 'both'
          oci-registry: 'ghcr.io/${{ github.repository_owner }}'
          oci-username: ${{ github.actor }}
          oci-token: ${{ secrets.GITHUB_TOKEN }}
          generate-docs: 'false'

      - name: Generate documentation
        id: docs
        uses: criteo/cola-plugin-action@v1
        with:
          plugins-directory: 'plugins'
          validate-only: 'false'
          generate-docs: 'true'
          docs-branch: 'gh-pages'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog
        id: changelog
        run: |
          cat << 'EOF' > RELEASE_NOTES.md
          # Release ${{ steps.version.outputs.tag }}

          ## 🎉 What's New

          This release includes updates to Command Launcher plugins.

          ## 📦 Available Plugins

          EOF

          # List all packaged plugins
          for archive in build/packages/*.tar.gz; do
            if [ -f "$archive" ]; then
              basename=$(basename "$archive" .tar.gz)
              sha256=$(sha256sum "$archive" | awk '{print $1}')
              echo "### ${basename}" >> RELEASE_NOTES.md
              echo "" >> RELEASE_NOTES.md
              echo "**SHA256:** \`${sha256}\`" >> RELEASE_NOTES.md
              echo "" >> RELEASE_NOTES.md
            fi
          done

          cat << 'EOF' >> RELEASE_NOTES.md

          ## 📥 Installation Instructions

          ### Method 1: Download from GitHub Releases

          ```bash
          # Download the plugin archive
          wget https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.tag }}/<plugin-name>-<version>.tar.gz

          # Extract to your plugins directory
          tar -xzf <plugin-name>-<version>.tar.gz -C ~/.command-launcher/plugins/

          # Verify installation
          cola plugin list
          ```

          ### Method 2: Pull from OCI Registry

          ```bash
          # Using ORAS
          oras pull ghcr.io/${{ github.repository_owner }}/<plugin-name>:${{ steps.version.outputs.version }}

          # Or pull the latest version
          oras pull ghcr.io/${{ github.repository_owner }}/<plugin-name>:latest
          ```

          ### Method 3: Using Command Launcher (if supported)

          ```bash
          # Install from OCI registry
          cola plugin install ghcr.io/${{ github.repository_owner }}/<plugin-name>:${{ steps.version.outputs.version }}
          ```

          ## 🔍 Verify Package Integrity

          ```bash
          # Verify SHA256 checksum
          sha256sum -c <plugin-name>-<version>.tar.gz.sha256
          ```

          ## 📚 Documentation

          Full documentation is available at:
          ${{ steps.docs.outputs.url }}

          ## 🐛 Known Issues

          None reported for this release.

          ## 🙏 Contributors

          Thank you to all contributors who made this release possible!

          ---

          🤖 *Automated release generated by [Cola Plugin Action](https://github.com/criteo/cola-plugin-action)*
          EOF

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.tag }}
          body_path: RELEASE_NOTES.md
          files: |
            build/packages/*.tar.gz
            build/packages/*.tar.gz.sha256
          draft: false
          prerelease: false
          generate_release_notes: true
          fail_on_unmatched_files: false  # Don't fail if some files are missing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true  # Don't fail if release already exists

      - name: Check if release already exists
        if: steps.create_release.outcome == 'failure'
        run: |
          echo "⚠️  Release may already exist or had issues"
          echo "Checking if release ${{ steps.version.outputs.tag }} exists..."

          release_info=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.version.outputs.tag }}")

          if echo "$release_info" | jq -e '.id' > /dev/null; then
            echo "✅ Release already exists: ${{ steps.version.outputs.tag }}"
            echo "This is not an error - the release is already published"
            exit 0
          else
            echo "❌ Release creation failed and release doesn't exist"
            exit 1
          fi

      - name: Publish to GitHub Container Registry
        run: |
          echo "✅ Plugins published to:"
          echo "  - GitHub Releases: https://github.com/${{ github.repository }}/releases/tag/${{ steps.version.outputs.tag }}"
          echo "  - OCI Registry: ghcr.io/${{ github.repository_owner }}"
          echo "  - Documentation: ${{ steps.docs.outputs.url }}"

      - name: Create summary
        run: |
          echo "## 🚀 Release ${{ steps.version.outputs.tag }} Published" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📦 Artifacts" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **GitHub Release:** [View Release](https://github.com/${{ github.repository }}/releases/tag/${{ steps.version.outputs.tag }})" >> $GITHUB_STEP_SUMMARY
          echo "- **OCI Registry:** \`ghcr.io/${{ github.repository_owner }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Documentation:** [View Docs](${{ steps.docs.outputs.url }})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📥 Quick Install" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "# Pull from OCI registry" >> $GITHUB_STEP_SUMMARY
          echo "oras pull ghcr.io/${{ github.repository_owner }}/<plugin-name>:${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "> **Note:** Re-running this workflow is safe - versions already in OCI registry or GitHub Releases are automatically skipped" >> $GITHUB_STEP_SUMMARY
