# ==============================================================================
# EXAMPLE WORKFLOW FOR PLUGIN REPOSITORIES
# ==============================================================================
# This is a template workflow for repositories that contain Command Launcher plugins.
# Copy this file to YOUR plugin repository at: .github/workflows/scheduled.yml
#
# DO NOT use this in the cola-plugin-action repository itself!
# ==============================================================================

name: Scheduled Plugin Maintenance

# This workflow runs on a schedule to keep documentation updated
# and verify all plugins remain valid

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  pages: write
  issues: write

jobs:
  # Validate all plugins
  validate-all:
    name: Validate All Plugins
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate all plugin manifests
        id: validate
        uses: criteo/cola-plugin-action@v1
        continue-on-error: true
        with:
          plugins-directory: 'plugins'
          validate-only: 'true'

      - name: Create issue if validation fails
        if: steps.validate.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'âš ï¸ Weekly Plugin Validation Failed',
              body: `## Plugin Validation Failed

              The scheduled weekly validation check has detected issues with one or more plugin manifests.

              **Workflow Run:** https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

              Please review and fix the following:
              1. Check the workflow logs for specific validation errors
              2. Update affected plugin manifests
              3. Ensure all required fields are present and valid

              This issue was automatically created by the scheduled maintenance workflow.`,
              labels: ['plugin-validation', 'automated']
            });

  # Regenerate documentation
  refresh-docs:
    name: Refresh Documentation
    runs-on: ubuntu-latest
    needs: validate-all

    steps:
      - uses: actions/checkout@v4

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Regenerate plugin documentation
        uses: criteo/cola-plugin-action@v1
        with:
          plugins-directory: 'plugins'
          validate-only: 'false'
          generate-docs: 'true'
          docs-branch: 'gh-pages'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Summary
        run: |
          echo "## âœ… Documentation Refreshed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Plugin documentation has been regenerated and published to GitHub Pages." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "ðŸ“š View at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> $GITHUB_STEP_SUMMARY
