# ==============================================================================
# EXAMPLE WORKFLOW FOR PLUGIN REPOSITORIES
# ==============================================================================
# This is a template workflow for repositories that contain Command Launcher plugins.
# Copy this file to YOUR plugin repository at: .github/workflows/release.yml
#
# DO NOT use this in the cola-plugin-action repository itself!
# ==============================================================================

name: Simple Plugin Release

# This is a simplified workflow for basic plugin validation and release
# Use this if you don't need OCI registry or advanced features

on:
  push:
    # Validate on pushes to ANY branch
    # Only main will create releases (controlled by job condition)
    paths:
      - 'plugins/**'
  pull_request:
    # Validate on ALL pull requests (regardless of target branch)
    paths:
      - 'plugins/**'

permissions:
  contents: write
  pages: write

jobs:
  # Validate on every PR and push
  validate:
    name: Validate Plugins
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate plugin manifests
        uses: criteo/cola-plugin-action@v1
        with:
          plugins-directory: 'plugins'
          validate-only: 'true'

  # Package and release only on main branch
  release:
    name: Package and Release
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Package plugins and generate docs
        uses: criteo/cola-plugin-action@v1
        with:
          plugins-directory: 'plugins'
          package-format: 'tar.gz'  # Creates ZIP for artifacts
          generate-docs: 'true'
          docs-branch: 'gh-pages'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          files: |
            build/packages/*.zip
            build/packages/*.zip.sha256
          fail_on_unmatched_files: false  # Don't fail if some files are missing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true  # Don't fail if release already exists (unlikely with run_number, but possible)

      - name: Release summary
        run: |
          echo "✅ Release completed"
          echo "Note: Versions already released are automatically skipped"
