name: 'Cola Plugin Action'
description: 'Validate, package, and publish Command Launcher plugins'
author: 'Alexander @ Criteo'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  packages-directory:
    description: 'Root directory containing plugin subdirectories'
    required: true
    default: 'packages'

  validate-only:
    description: 'Only validate manifests without packaging'
    required: false
    default: 'false'

  package-format:
    description: 'Package format: zip (creates ZIP archives), oci (pushes to OCI registry), or both'
    required: false
    default: 'zip'

  oci-registry:
    description: 'OCI registry URL (e.g., ghcr.io/username)'
    required: false
    default: ''

  oci-username:
    description: 'OCI registry username'
    required: false
    default: ''

  oci-token:
    description: 'OCI registry token/password'
    required: false
    default: ''

  github-token:
    description: 'GitHub token for creating individual releases for each plugin (format: plugin-name-version)'
    required: false
    default: ''

outputs:
  validated-packages:
    description: 'JSON array of validated package directories'

  valid-count:
    description: 'Number of valid packages'

  invalid-count:
    description: 'Number of invalid packages'

  packaged-artifacts:
    description: 'JSON array of created artifact paths with metadata'

  package-count:
    description: 'Number of packages created'

runs:
  using: 'node20'
  main: 'dist/index.js'
