name: 'Cola Plugin Action'
description: 'Validate, package, and publish Command Launcher plugins'
author: 'Alexander @ Criteo'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  plugins-directory:
    description: 'Root directory containing plugin subdirectories'
    required: true
    default: 'packages'

  validate-only:
    description: 'Only validate manifests without packaging'
    required: false
    default: 'false'

  package-format:
    description: 'Package format: tar.gz (creates ZIP for artifacts), oci (no artifacts), or both'
    required: false
    default: 'tar.gz'

  oci-registry:
    description: 'OCI registry URL (e.g., ghcr.io/username)'
    required: false
    default: ''

  oci-username:
    description: 'OCI registry username'
    required: false
    default: ''

  oci-token:
    description: 'OCI registry token/password'
    required: false
    default: ''

  generate-docs:
    description: 'Generate documentation pages from GitHub Release assets'
    required: false
    default: 'true'

  docs-branch:
    description: 'Branch to push documentation'
    required: false
    default: 'gh-pages'

  docs-keep-versions:
    description: 'Number of versions to keep per plugin (0 = keep all versions)'
    required: false
    default: '0'

  github-token:
    description: 'GitHub token for pushing to gh-pages and accessing releases'
    required: false
    default: ${{ github.token }}

outputs:
  validated-plugins:
    description: 'JSON array of validated plugin directories'

  valid-count:
    description: 'Number of valid plugins'

  invalid-count:
    description: 'Number of invalid plugins'

  packaged-artifacts:
    description: 'JSON array of created artifact paths with metadata'

  package-count:
    description: 'Number of packages created'

  docs-url:
    description: 'URL to generated documentation'

runs:
  using: 'node20'
  main: 'dist/index.js'
