#!/usr/bin/env bash

set -euo pipefail

# test-docs-locally.sh
# Generates documentation locally for testing without pushing to GitHub

# Get the directory where the script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Source common functions
# shellcheck source=./common.sh
source "${SCRIPT_DIR}/common.sh"
# shellcheck source=./common-docs.sh
source "${SCRIPT_DIR}/common-docs.sh"

log_header "Testing Documentation Generation Locally"

# Configuration
PLUGINS_DIR="${PLUGINS_DIR:-tests/fixtures}"
TEMPLATE_PATH="${TEMPLATE_PATH:-templates/plugin-page.html}"
OUTPUT_DIR="${OUTPUT_DIR:-build/docs}"

log_info "Plugins directory: $PLUGINS_DIR"
log_info "Template: $TEMPLATE_PATH"
log_info "Output directory: $OUTPUT_DIR"

# Clean previous output
if [[ -d "$OUTPUT_DIR" ]]; then
    log_info "Cleaning previous output..."
    rm -rf "$OUTPUT_DIR"
fi

# Create output directory
mkdir -p "$OUTPUT_DIR"
cd "$OUTPUT_DIR"

# Initialize as git repo (required by generate-docs.sh)
git init -q
git config user.name "Test User"
git config user.email "test@example.com"

# Create plugins directory
mkdir -p plugins

log_section "Generating Documentation"

# Copy template to accessible location
export GITHUB_WORKSPACE="$PROJECT_ROOT"
export TEMPLATE_PATH="$PROJECT_ROOT/$TEMPLATE_PATH"
export DOCS_BRANCH="main"

# Save original PLUGINS_DIR before modifying
ORIG_PLUGINS_DIR="$PLUGINS_DIR"
export PLUGINS_DIR="$PROJECT_ROOT/$PLUGINS_DIR"

# Check if pandoc is available
if command -v pandoc &> /dev/null; then
    log_success "Pandoc detected - will use for better markdown conversion"
else
    log_warning "Pandoc not found - using basic markdown rendering"
    log_info "Install with: brew install pandoc (macOS) or apt-get install pandoc (Linux)"
fi

# Track plugin cards for index
declare -a plugin_cards=()

# Process all plugins and generate documentation
process_plugins_for_docs "$PLUGINS_DIR" "$TEMPLATE_PATH" plugin_cards

# Generate index page
log_info "Generating index page..."
generate_index_page "index.html" "Command Launcher Plugins" "Local Documentation Preview" plugin_cards "true" "Local preview generated by Cola Plugin Action"

# Return to project root
cd "$PROJECT_ROOT"

# Summary
log_header "Documentation Generated Successfully"

echo "Location: $OUTPUT_DIR/"
echo ""
echo "Generated files:"
ls -1 "$OUTPUT_DIR"/*.html 2>/dev/null | sed 's/^/  - /'
ls -1 "$OUTPUT_DIR"/plugins/*.html 2>/dev/null | sed 's/^/  - /'

echo ""
log_section "Opening in Browser"

# Open in browser (skip if SKIP_BROWSER is set)
if [[ -z "${SKIP_BROWSER:-}" ]]; then
    if command -v open &> /dev/null; then
        # macOS
        open "$OUTPUT_DIR/index.html"
        log_success "Opened in default browser (macOS)"
    elif command -v xdg-open &> /dev/null; then
        # Linux
        xdg-open "$OUTPUT_DIR/index.html"
        log_success "Opened in default browser (Linux)"
    elif command -v start &> /dev/null; then
        # Windows
        start "$OUTPUT_DIR/index.html"
        log_success "Opened in default browser (Windows)"
    else
        log_warning "Could not auto-open browser"
        echo ""
        echo "Manually open: file://$(pwd)/$OUTPUT_DIR/index.html"
    fi
else
    log_info "Skipping browser open (SKIP_BROWSER is set)"
    echo ""
    echo "Open manually: file://$(cd "$PROJECT_ROOT" && pwd)/$OUTPUT_DIR/index.html"
fi

echo ""
log_info "To serve with live server:"
echo "  cd $OUTPUT_DIR"
echo "  python3 -m http.server 8000"
echo "  # Then open http://localhost:8000"

exit 0
